type trivia = {
  question : string;
  answer : string;
}

let get_question tr = tr.question

let get_answer tr = tr.answer

let correct tr ans animal = 
  if String.lowercase_ascii ans = String.lowercase_ascii tr.answer then
    (Pet.increase_money animal 1.0; true)
  else (Pet.decrease_money animal 1.0; false)

let trivia_questions =
  [
    { question = "What is the largest planet in our solar system?";
      answer = "Jupiter"};
    { question = "What year did the Titanic sink?";
     answer = "1912"};
    { question = "What is the normal body temperature for a dog? (in Celsius)";
      answer = "38"};
    { question = "How many legs does a spider have?"; 
      answer = "8" };
    { question = "Who wrote 'To Kill a Mockingbird'?";
      answer = "Harper Lee" };
    { question = "What is the capital of France?"; 
      answer = "Paris" };
    { question = "What chemical element has the symbol O?"; 
      answer = "Oxygen" };
    { question = "In what year did the First World War begin?";
      answer = "1914"};
    { question = "What is the largest ocean on Earth?"; 
      answer = "Pacific" };
    { question = "What is the hardest natural substance on Earth?";
      answer = "Diamond"};
    { question = "What planet is known as the Red Planet?"; 
      answer = "Mars" };
    { question = "Who painted the Mona Lisa?"; 
      answer = "Leonardo da Vinci" };
    { question = "What is the smallest breed of dog?"; 
      answer = "Chihuahua" };
    { question = "What is the main ingredient in guacamole?";
      answer = "Avocado"};
    { question = "How many hearts does an octopus have?"; 
      answer = "Three" };
    { question = "What is the longest river in the world?"; 
      answer = "Nile" };
    { question = "What is the fastest land animal?"; 
      answer = "Cheetah" };
    { question = "What year was the first iPhone released?"; 
      answer = "2007"};
    { question = "Who wrote 'Pride and Prejudice'?"; 
      answer = "Jane Austen" };
    { question = "What is the tallest breed of dog in the world?";
      answer = "Great Dane"};
    { question = "What color is a giraffe's tongue?"; 
      answer = "Blue" };
    { question = "What gas do plants absorb from the atmosphere?";
      answer = "Carbon dioxide"};
    { question = "What is the smallest planet in our solar system?";
      answer = "Mercury"};
    { question = "What year did World War II end?"; 
      answer = "1945" };
    { question = "Who discovered penicillin?"; 
      answer = "Alexander Fleming"};
    { question = "What is the capital of Canada?"; 
      answer = "Ottawa"};
    { question = "Who wrote '1984'?"; 
      answer = "George Orwell"};
    { question = "What is the chemical symbol for gold?"; 
      answer = "Au" };
    { question = "What year did the Berlin Wall fall?"; 
      answer = "1989" };
    { question = "How many valves does the heart have?"; 
      answer = "4" };
    { question = "What is the largest bird of prey in the world?";
      answer = "Andean condor"};
    { question = "What organ can regenerate tissue?"; 
      answer = "Liver"};
    { question = "What is the main ingredient in traditional Japanese miso soup?";
      answer = "Soy"};
    { question = "What element is diamond made of?"; 
      answer = "Carbon" };
    { question = "What year did Albert Einstein win the Nobel Prize in Physics?";
      answer = "1921"};
    { question = "What is the longest-running Broadway show of all time?";
      answer = "The Phantom of the Opera"};
    { question = "Who invented the telephone?";
      answer = "Alexander Graham Bell"};
    { question = "What is the gestation period of an African elephant?";
      answer = "22 months"};
    { question = "Which planet is closest to the sun?"; 
      answer = "Mercury" };
    { question = "What is the smallest bone in the human body?";
      answer = "Stapes"};
    { question = "Who painted 'The Starry Night'?";
      answer = "Vincent van Gogh"};
    { question = "What is the most abundant gas in the Earth's atmosphere?";
      answer = "Nitrogen"};
    { question = "Who is known as the father of modern physics?";
      answer = "Galileo Galilei"};
    { question = "What year did the American Civil War end?"; 
      answer = "1865" };
    { question = "Who wrote 'Les Misérables'?"; 
      answer = "Victor Hugo" };
    { question = "What is the capital of Iceland?"; 
      answer = "Reykjavik"};
    { question =  "What vitamin is produced when a person is exposed to sunlight?";
      answer = "Vitamin D"};
    { question = "What is the study of mushrooms called?"; 
      answer = "Mycology"};
    { question = "Which animal has the highest blood pressure?";
      answer = "Giraffe"};
    { question = "Who discovered gravity when he saw a falling apple?";
      answer = "Isaac Newton"};
    { question = "What is the most spoken language in the world?";
      answer = "Mandarin"};
    { question =  "What animal is known to have the most powerful bite in the world?";
      answer = "Saltwater crocodile"};
    { question = "What is the second longest river in the world?";
      answer = "Amazon River"};
  ]